using System;
using System.Collections.Generic;
using System.Text;

namespace Verse
{
    /// <summary>One batch of identical creatures inside a wave.</summary>
    internal struct ArenaGroup
    {
        /// <summary>Vanilla prefab name, as <c>ZNetScene</c> knows it.</summary>
        internal string Prefab;
        internal int Count;
        /// <summary>Stars. 1 is an ordinary creature; the ZDO field is only written above 1.</summary>
        internal int Level;
        /// <summary>
        /// A miniboss rather than an add. The player multiplier deliberately does not apply to
        /// these - see <see cref="Scale"/>.
        /// </summary>
        internal bool Boss;
    }

    /// <summary>One item in the loaner kit.</summary>
    internal struct KitItem
    {
        internal string Prefab;
        internal int Stack;
        /// <summary>Upgrade level, 1 being un-upgraded.</summary>
        internal int Quality;
    }

    /// <summary>
    /// The arena's numbers, with no Unity in them, so <c>./test.sh</c> can cover the parts that
    /// are easy to get quietly wrong - the multiplier edges, the cap, and what the capstone
    /// escalates to. Same reason <see cref="SleepRule"/> and <see cref="CommandText"/> are
    /// separate from the code that calls them.
    ///
    /// <para>Every prefab name here was taken from this server's own object index
    /// (<c>HallPatton.knowledge.txt</c>, generated by walking <c>ObjectDB</c> and
    /// <c>ZNetScene.m_prefabs</c> on the live box) rather than from memory, and the health
    /// figures in the comments are that index's. See docs/arena-design.md for why each wave is
    /// shaped the way it is.</para>
    /// </summary>
    internal static class ArenaRules
    {
        internal const int Waves = 25;

        /// <summary>Hard ceiling on the add multiplier, whatever the party size.</summary>
        internal const float MultiplierCap = 4.0f;

        /// <summary>
        /// Most creatures one wave may put in the ring, however big the party.
        ///
        /// <para>Wave 25 is already 34 bodies solo, and four times that is 136 creatures all
        /// simulated by clients with every damage RPC crossing one relay on one main thread.
        /// Spike F has never been measured, so this is the guess that keeps an unmeasured thing
        /// from being the first measurement a full party takes.</para>
        /// </summary>
        internal const int MaxPerWave = 70;

        /// <summary>
        /// The waves, as a solo player meets them.
        ///
        /// <para><b>One faction per wave.</b> Valheim creatures belong to factions and different
        /// factions are hostile to each other, so a wave of greydwarves and stone golems spends
        /// its time fighting itself instead of the player - which the first playtest reported
        /// exactly. Diversity comes from changing faction every five waves rather than from
        /// mixing them inside one wave, and <c>ArenaSelfTest</c> reads
        /// <c>Character.m_faction</c> off every prefab and fails if any wave is mixed, so these
        /// groupings are checked rather than assumed.</para>
        ///
        /// <para><b>A smooth ramp.</b> The first table was flat to wave 7 and then a cliff at 8,
        /// which is the other thing the playtest reported. This one climbs about 1.2x a wave all
        /// the way, with a miniboss on every fifth as a punctuation mark.</para>
        ///
        /// <para>Health totals in the comments are the sum at one player, so a change that
        /// doubles a wave by accident is visible in review.</para>
        /// </summary>
        private static readonly ArenaGroup[][] Table =
        {
            // --- 1-5: Black Forest. ForestMonsters ----------------------------------------
            new[] { G("Greyling", 6) },                                             //   120
            new[] { G("Greyling", 5), G("Greydwarf", 3) },                          //   220
            new[] { G("Greydwarf", 6), G("Greyling", 4) },                          //   320
            new[] { G("Greydwarf", 8), G("Greydwarf_Shaman", 2) },                   //   440
            new[] { G("Troll", 1, boss: true), G("Greydwarf", 2) },                  //   680

            // --- 6-10: Swamp and crypts. Undead -------------------------------------------
            new[] { G("Skeleton", 16), G("Skeleton_Poison", 2) },                    //   840
            new[] { G("Draugr", 8), G("Skeleton", 6) },                              // 1,040
            new[] { G("Draugr", 10), G("Wraith", 3) },                               // 1,300
            new[] { G("Draugr", 12), G("Draugr_Elite", 2) },                         // 1,600
            new[] { G("Skeleton_Hildir_nochest", 1, boss: true),
                    G("Draugr", 10), G("Wraith", 3) },                               // 1,900

            // --- 11-15: Mountain. MountainMonsters ----------------------------------------
            //
            // Five waves that were all the same wave. This block used to run 22 wolves, then 12,
            // then 12, then 14, then 6 - and a player who died on wave 14 reported it as
            // back-to-back-to-back, which the table agrees with: 66 wolves across five waves and
            // nothing new in them after the first. It is now 37 wolves, fifteen of them starred,
            // and each wave has its own shape - a pack, cultists at range, drakes overhead, a
            // warband, the boss. Every wave's total health is within about 3% of what it replaced,
            // because the complaint was that the block was dull and not that it was hard.
            //
            // Stone golems and bears are ForestMonsters, not Mountain - the self-test caught both
            // of those waves fighting themselves. Wolves, Ulvs, Fenrings, Cultists and Drakes are
            // all MountainMonsters: they share the peaks and the frost caves in the live world
            // without fighting each other, and CheckFactions re-confirms it on every boot.
            //
            // Health a body, from the server's own object index: Wolf 80, Ulv 50, Fenring 300,
            // Cultist 200, Drake 100. A star doubles it.

            // The pack: many light bodies and a few leaders, rather than a wall of wolves.
            new[] { G("Wolf", 10), G("Ulv", 16), G("Wolf", 4, level: 2) },           // 2,240

            // Cultists breathe fire from where they stand - the first thing in the block that
            // cannot be answered by walking straight into it.
            new[] { G("Fenring", 5), G("Fenring_Cultist", 4), G("Wolf", 6) },        // 2,780

            // Drakes, the Mountain's only ranged threat, over a floor of Ulvs that starred
            // wolves are leading. The kit's bow is in it for waves like this one.
            //
            // Three and no more, because a flyer is the one thing that can stall a wave: a wave
            // ends when its creatures' ZDOs are gone, and nothing brings back a drake that has
            // drifted out of reach over the wall. Wave 18's deathsquitos have had the same
            // exposure since the table was written and have not done it, which is the only
            // evidence there is. If it ever happens, the fix is a leash in Arena.Fight - a
            // spawned creature outside the ring for long enough counts as dead - not fewer drakes.
            new[] { G("Hatchling", 3), G("Fenring", 4), G("Ulv", 12),
                    G("Wolf", 6, level: 2) },                                        // 3,060

            // The warband, and the wave the complaint was about: the same total health as the
            // fourteen-wolf version, spread across four species.
            new[] { G("Fenring", 6), G("Fenring_Cultist", 4), G("Ulv", 12),
                    G("Wolf", 5, level: 2) },                                        // 4,000

            // His own cultists with him, and no stars among the adds: a star raises damage as
            // well as health, and the boss is already the hard part of this wave.
            new[] { G("Fenring_Cultist_Hildir_nochest", 1, boss: true),
                    G("Fenring", 4), G("Fenring_Cultist", 3), G("Wolf", 6) },        // 4,130

            // --- 16-20: Plains. PlainsMonsters --------------------------------------------
            // There is no "Growth" prefab: that is the trophy's name, and the creature is BlobTar.
            // So for as long as this wave said Growth it quietly spawned four creatures short -
            // 4,450 against the 4,850 the comment claimed - which the self-test's new "every
            // creature exists" check found on the first boot after it was added.
            //
            // BlobTar is not the fix, though, and the live faction map is why: BlobTar=Undead,
            // like every other blob, so four of them in a Plains wave is a wave that fights
            // itself. Tried, caught by CheckFactions on the next boot, reverted. The 400 health
            // goes back as two more Fulings and four Deathsquitos, which keeps something in the
            // wave that is not a Fuling - the whole point of the group - and keeps it Plains.
            new[] { G("Goblin", 24), G("GoblinShaman", 6), G("Deathsquito", 4) },    // 4,840
            new[] { G("GoblinBrute", 3), G("Goblin", 16), G("GoblinShaman", 4) },    // 5,600
            new[] { G("Lox", 3), G("Goblin", 18), G("Deathsquito", 6) },             // 6,210
            new[] { G("GoblinBrute", 5), G("Goblin", 16), G("GoblinShaman", 6) },    // 7,400
            new[] { G("GoblinBruteBros_nochest", 1, boss: true),
                    G("GoblinBrute", 3), G("Goblin", 14), G("GoblinShaman", 4) },    // 7,350

            // --- 21-25: Mistlands. The end. Stars rather than more bodies -----------------
            new[] { G("Seeker", 14, level: 2), G("SeekerBrood", 14), G("Tick", 8) }, //  ~6,500
            new[] { G("SeekerBrute", 3), G("Seeker", 14, level: 2), G("Tick", 10) }, //  ~9,900
            new[] { G("Gjall", 2), G("Seeker", 16, level: 2), G("Tick", 10) },       // ~10,400
            new[] { G("SeekerBrute", 4), G("Gjall", 1), G("Seeker", 12, level: 2) }, // ~11,500
            new[] { G("SeekerBrute", 4, boss: true), G("Gjall", 2, boss: true),
                    G("Seeker", 12, level: 2), G("SeekerBrood", 16) },               // ~12,500
        };

        /// <summary>
        /// Extra minibosses on the capstone as the party grows, because multiplying a miniboss is
        /// nonsense - four Zil-and-Thungrs is not a harder fight, it is a slideshow. The index is
        /// the number of *additional* bosses, so this escalates rather than replaces.
        ///
        /// <para>All Mistlands, because the last wave is Mistlands and a Hildir miniboss from
        /// another faction would stand in the ring fighting the seekers instead of the players.</para>
        /// </summary>
        private static readonly string[] CapstoneExtras =
        {
            "SeekerBrute",      // 4-5 players
            "Gjall",            // 6-8 players
            "SeekerBrute",      // 9-12 players
        };

        private static ArenaGroup G(string prefab, int count, int level = 1, bool boss = false) =>
            new ArenaGroup { Prefab = prefab, Count = count, Level = level, Boss = boss };

        /// <summary>
        /// How much to multiply the adds by for a party of <paramref name="players"/>.
        ///
        /// <para><b>Sub-linear on purpose.</b> Co-op power in Valheim is super-linear - a tank
        /// and an archer are worth far more than two of either - so a linear multiplier makes
        /// a full party's run easier than a solo one, not harder. Clamped at both ends: a
        /// nonsense player count must not produce a nonsense wave.</para>
        /// </summary>
        internal static float Multiplier(int players)
        {
            if (players <= 1) return 1.0f;
            if (players == 2) return 1.5f;
            if (players == 3) return 2.3f;
            if (players <= 5) return 2.8f;
            if (players <= 8) return 3.4f;
            return MultiplierCap;
        }

        /// <summary>How many extra capstone minibosses a party of this size faces.</summary>
        internal static int ExtraBosses(int players)
        {
            if (players <= 3) return 0;
            if (players <= 5) return 1;
            if (players <= 8) return 2;
            return 3;
        }

        /// <summary>
        /// What actually gets spawned for wave <paramref name="wave"/> (1-based) with
        /// <paramref name="players"/> in the ring. Adds are multiplied and rounded up; bosses
        /// are not multiplied, and the capstone gains whole extra minibosses instead.
        /// </summary>
        internal static ArenaGroup[] Scale(int wave, int players)
        {
            if (wave < 1 || wave > Waves) return new ArenaGroup[0];

            ArenaGroup[] baseline = Table[wave - 1];
            float m = Multiplier(players);

            var result = new List<ArenaGroup>(baseline.Length + 3);
            foreach (ArenaGroup group in baseline)
            {
                ArenaGroup scaled = group;
                if (!group.Boss)
                    scaled.Count = Math.Max(1, (int)Math.Ceiling(group.Count * m));
                result.Add(scaled);
            }

            if (wave == Waves)
            {
                int extras = Math.Min(ExtraBosses(players), CapstoneExtras.Length);
                for (int i = 0; i < extras; i++)
                    result.Add(G(CapstoneExtras[i], 1, boss: true));
            }

            return Cap(result);
        }

        /// <summary>
        /// Trims a wave back to <see cref="MaxPerWave"/> if the multiplier has run away with it,
        /// taking it out of the adds and never the bosses - losing a Gjall changes the fight,
        /// losing four of twenty seekers does not.
        /// </summary>
        private static ArenaGroup[] Cap(List<ArenaGroup> groups)
        {
            int total = 0, adds = 0;
            foreach (ArenaGroup g in groups)
            {
                total += g.Count;
                if (!g.Boss) adds += g.Count;
            }

            if (total <= MaxPerWave || adds == 0) return groups.ToArray();

            // How much of the adds has to go, as a fraction.
            float keep = Math.Max(0f, (MaxPerWave - (total - adds)) / (float)adds);

            for (int i = 0; i < groups.Count; i++)
            {
                if (groups[i].Boss) continue;

                ArenaGroup g = groups[i];
                g.Count = Math.Max(1, (int)Math.Floor(g.Count * keep));
                groups[i] = g;
            }

            return groups.ToArray();
        }

        /// <summary>Total creatures in a wave, for the log line and the load question.</summary>
        internal static int Size(int wave, int players)
        {
            int total = 0;
            foreach (ArenaGroup group in Scale(wave, players)) total += group.Count;
            return total;
        }

        /// <summary>
        /// The loaner kit: Mistlands tier.
        ///
        /// <para><b>The food is not decoration.</b> An unfed Valheim player has 25 health and
        /// wave 1 would kill them. The Mistlands trio - Misthare Supreme, Seeker Aspic and
        /// Mushroom Omelette - is what every wave above is tuned against, and they have to
        /// actually eat it, so the countdown says so.</para>
        ///
        /// <para><b>The omelette is the staff's ammunition, and that is why it is in the
        /// trio.</b> Eitr is granted by food and by nothing else, so a Staff of Embers in the
        /// kit is an ornament unless one of the three slots is an eitr food. Mushroom Omelette
        /// is that slot - it took Yggdrasil Porridge's place rather than being added, because
        /// a Valheim player has exactly three food slots. The cost is the porridge's stamina;
        /// Seeker Aspic carries that now.</para>
        ///
        /// <para><b>One of each weapon, covering three damage types.</b> Mistwalker for slash,
        /// Demolisher for the blunt-weak skeletons that slash does badly against, and the
        /// Staff of Embers for fire. Weapons do not stack, so each is its own entry rather than
        /// a stack - an ItemData carrying m_stack = 3 on a one-per-slot item is not a thing the
        /// game expects. There are deliberately no durability spares: that is a run-ending
        /// technicality over twenty-five waves, and if it starts happening the answer is spares
        /// here again, not a quieter failure.</para>
        /// </summary>
        internal static KitItem[] Kit(bool cold)
        {
            var kit = new List<KitItem>
            {
                K("SwordMistwalker", 1, 3),
                K("SledgeDemolisher", 1, 3),
                K("StaffFireball", 1, 3),

                // 96 block at base, and quality 3 on top: enough to parry a troll.
                K("ShieldCarapace", 1, 3),

                K("BowSpineSnap", 1, 2),
                K("ArrowCarapace", 60),

                // Carapace is 32 armour a piece against iron's 14, quality 3 again.
                K("HelmetCarapace", 1, 3),
                K("ArmorCarapaceChest", 1, 3),
                K("ArmorCarapaceLegs", 1, 3),

                K("MisthareSupreme", 3),
                K("SeekerAspic", 3),
                K("MushroomOmelette", 3),

                // A full stack each. Loadout.Build clamps to the prefab's own m_maxStackSize,
                // so this asks for ten and gets ten or whatever the real ceiling turns out to
                // be - it cannot write an over-stacked item.
                K("MeadHealthMajor", 10),
                K("MeadStaminaLingering", 10),
            };

            // Only when the arena is sited somewhere that freezes. Carapace does not keep the
            // cold out any better than iron did.
            if (cold) kit.Add(K("MeadFrostResist", 2));

            return kit.ToArray();
        }

        private static KitItem K(string prefab, int stack, int quality = 1) =>
            new KitItem { Prefab = prefab, Stack = stack, Quality = quality };

        /// <summary>mm:ss, because a run is minutes and nobody reads 437 seconds.</summary>
        internal static string Clock(float seconds)
        {
            if (seconds < 0f) seconds = 0f;
            int whole = (int)seconds;
            return (whole / 60) + ":" + (whole % 60).ToString("00");
        }

        /// <summary>
        /// The line broadcast to the whole server when a run ends. There is no leaderboard, so
        /// this is the entire reward, and it is written to be worth reading.
        /// </summary>
        internal static string Result(string who, int reached, bool cleared, float seconds, int players)
        {
            var sb = new StringBuilder();
            sb.Append(who);

            if (cleared)
                sb.Append(" cleared all ").Append(Waves).Append(" waves of the arena");
            else
                sb.Append(" fell on wave ").Append(reached).Append(" of ").Append(Waves);

            sb.Append(" in ").Append(Clock(seconds));
            if (players > 1) sb.Append(", ").Append(players).Append("-handed");
            sb.Append('.');

            return sb.ToString();
        }

        /// <summary>
        /// A one-line summary of a wave, for the chat announcement. Deliberately names the
        /// creatures: "wave 7 of 10" tells a player nothing, "2 trolls and 24 greydwarves"
        /// tells them what to do about it.
        /// </summary>
        internal static string Describe(int wave, int players)
        {
            ArenaGroup[] groups = Scale(wave, players);
            var sb = new StringBuilder();
            sb.Append("Wave ").Append(wave).Append(" of ").Append(Waves).Append(':');

            for (int i = 0; i < groups.Length; i++)
            {
                sb.Append(i == 0 ? " " : ", ");
                sb.Append(groups[i].Count).Append("x ").Append(groups[i].Prefab);
                if (groups[i].Level > 1) sb.Append(" (").Append(groups[i].Level - 1).Append("-star)");
            }

            return sb.ToString();
        }
    }
}
