namespace Verse
{
    /// <summary>
    /// The verse tag on a networked object, and the rule for who may see it.
    ///
    /// The tag lives in the ZDO's own field set rather than in a table beside it, for one
    /// reason: ZDO fields are written to the world save by vanilla code, so verse membership
    /// survives a restart with no persistence of our own and no chance of our table and the
    /// world drifting apart.
    ///
    /// Writing a field on a ZDO the server does not own is sanctioned - <c>ZDO.Set</c> takes
    /// an <c>okForNotOwner</c> flag, and the 1.0.16 body ignores it entirely and writes
    /// regardless. The field set is per-key, so the owning client's own writes never clear
    /// ours.
    /// </summary>
    internal static class ZdoVerse
    {
        /// <summary>Deliberately verbose: ZDO keys share one namespace with the whole game.</summary>
        private static readonly int Key = "verse.id".GetStableHashCode();

        internal static int Of(ZDO zdo) =>
            zdo == null ? Verses.None : zdo.GetInt(Key, Verses.None);

        internal static void Set(ZDO zdo, int verse)
        {
            if (zdo == null || verse == Verses.None) return;
            zdo.Set(Key, verse, okForNotOwner: true);
        }

        /// <summary>
        /// Whether a peer in <paramref name="viewerVerse"/> may be told this object exists.
        ///
        /// Untagged objects stay visible to everyone. That is the deliberate choice for this
        /// spike and it is also what makes it readable: terrain, vegetation and locations are
        /// generated by vanilla code that knows nothing about verses, so they are untagged and
        /// shared, and anything a *player* caused is tagged and private. Making generated
        /// content per-verse is a separate piece of work (see the design doc, spike 3).
        /// </summary>
        internal static bool VisibleTo(ZDO zdo, int viewerVerse)
        {
            int owner = Of(zdo);

            // Shared world content, unless this verse has changed it and so been given its
            // own divergent view - see HideMask.
            if (owner == Verses.None) return !HideMask.HiddenFrom(zdo, viewerVerse);

            return owner == viewerVerse;
        }

        /// <summary>
        /// Note there is deliberately no "inherit from the current owner" helper here.
        /// Ownership is reassigned to whoever is standing nearest (see <see cref="Authorship"/>),
        /// so it identifies a simulator, not an author, and tagging from it tags the whole
        /// landscape. A verse is assigned once, where the object is created.
        /// </summary>
        internal static bool Tagged(ZDO zdo) => Of(zdo) != Verses.None;
    }
}
